steps:
  # Run the Maven build
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world-java:0.0.2.RELEASE', '.']	
images: ['gcr.io/$PROJECT_ID/hello-world-java:0.0.2.RELEASE']